### ISSUE TITLE
Shitty architecture

### ISSUE THREAD

**Issue by 0lejk4** [0lejk4/solid.docs#13]
After looking at our code base i saw that we got poor architecture that is standing on stuff like busboy and etc which are concrete implementations. I think we need to go simpler and operate on plain strings or bytes. So user requests would look more like this:
``` json
{
 "file": "person.json",
 "action": "ADD_FIELD",
 "data": {
   "line": 15,
   "field": "name:'Sanya'"
}}
```
So we have one endpoint that awaits commands, passes them to some command handler manager that finds sufficient handler for such type of commands and type of files and does all of the actions

**Comment by vitpavlenko** [comment]
does not help, still feels shitty

**Comment by 0lejk4** [comment]
Congrats on solving this one!

**Comment by antonmyronyuk** [comment]
congrats guys

**Comment by vitpavlenko** [comment]
the best day in my life

**Comment by antonmyronyuk** [comment]
close it
